
xx:
	g++ -oxx main.cpp baselib/multi_threads/ThreadPoolManager.cpp baselib/multi_threads/ThreadPool.cpp baselib/multi_threads/Thread.cpp baselib/network_thread/NetworkThread.cpp --std=c++11 -pthread -levent -levent_core



